static const char *g_shader_fragment_quad = ""
#if defined(USE_LD)
"quad.frag.glsl"
#else
"layout(location=8)uniform sampler2D s;"
"layout(location=9)uniform sampler2D y;"
"varying vec3 c;"
"varying vec2 g;"
"float p(vec2 e)"
"{"
"return .2/(333.1-texture(y,e).r*332.9);"
"}"
"void main()"
"{"
"float a=1-b*.8,t=dot(normalize(c),n)*.5+.5;"
"vec3 n=mix(vec3(.6),vec3(1,1,.9),pow(t,7)+l(c*.05)*.05)*a;"
"float r=p(g),i=abs(o[4].r/255.-r);"
"vec4 c=vec4(0);"
"for(float o=0;"
"o<6.28;"
"o+=.314)"
"{"
"vec2 v=g+vec2(cos(o),sin(o))*i*.01;"
"vec4 e=texture(s,v,i*3);"
"e.rgb=mix(e.rgb,n,r)-mix(0,r*.9+.1,1-t),e.a+=.1,c+=vec4(e.rgb*e.a,e.a);"
"}"
"c.rgb/=c.a;"
"float v=pow(abs(float(o[5].r)/o[5].g-.5)*2,8);"
"gl_FragColor=vec4(mix(c.rgb,vec3(.4*a),mix(mix(.0,v,r),v,v)),1);"
"}"
#endif
"";
